/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as MonoRouteImport } from './routes/mono'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as ShareTokenRouteImport } from './routes/share.$token'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as DashboardTeamSlugRouteImport } from './routes/dashboard/$teamSlug'
import { Route as DashboardTeamSlugIndexRouteImport } from './routes/dashboard/$teamSlug.index'
import { Route as DashboardTeamSlugSettingsRouteImport } from './routes/dashboard/$teamSlug.settings'
import { Route as DashboardTeamSlugProjectIdRouteImport } from './routes/dashboard/$teamSlug.$projectId'
import { Route as DashboardTeamSlugProjectIdIndexRouteImport } from './routes/dashboard/$teamSlug.$projectId.index'
import { Route as DashboardTeamSlugProjectIdVideoIdRouteImport } from './routes/dashboard/$teamSlug.$projectId.$videoId'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const MonoRoute = MonoRouteImport.update({
  id: '/mono',
  path: '/mono',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => SignUpRoute,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => SignInRoute,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTeamSlugRoute = DashboardTeamSlugRouteImport.update({
  id: '/$teamSlug',
  path: '/$teamSlug',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTeamSlugIndexRoute = DashboardTeamSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardTeamSlugRoute,
} as any)
const DashboardTeamSlugSettingsRoute =
  DashboardTeamSlugSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => DashboardTeamSlugRoute,
  } as any)
const DashboardTeamSlugProjectIdRoute =
  DashboardTeamSlugProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => DashboardTeamSlugRoute,
  } as any)
const DashboardTeamSlugProjectIdIndexRoute =
  DashboardTeamSlugProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardTeamSlugProjectIdRoute,
  } as any)
const DashboardTeamSlugProjectIdVideoIdRoute =
  DashboardTeamSlugProjectIdVideoIdRouteImport.update({
    id: '/$videoId',
    path: '/$videoId',
    getParentRoute: () => DashboardTeamSlugProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/mono': typeof MonoRoute
  '/sign-in': typeof SignInRouteWithChildren
  '/sign-up': typeof SignUpRouteWithChildren
  '/dashboard/$teamSlug': typeof DashboardTeamSlugRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/share/$token': typeof ShareTokenRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/$teamSlug/$projectId': typeof DashboardTeamSlugProjectIdRouteWithChildren
  '/dashboard/$teamSlug/settings': typeof DashboardTeamSlugSettingsRoute
  '/dashboard/$teamSlug/': typeof DashboardTeamSlugIndexRoute
  '/dashboard/$teamSlug/$projectId/$videoId': typeof DashboardTeamSlugProjectIdVideoIdRoute
  '/dashboard/$teamSlug/$projectId/': typeof DashboardTeamSlugProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mono': typeof MonoRoute
  '/sign-in': typeof SignInRouteWithChildren
  '/sign-up': typeof SignUpRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/share/$token': typeof ShareTokenRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/$teamSlug/settings': typeof DashboardTeamSlugSettingsRoute
  '/dashboard/$teamSlug': typeof DashboardTeamSlugIndexRoute
  '/dashboard/$teamSlug/$projectId/$videoId': typeof DashboardTeamSlugProjectIdVideoIdRoute
  '/dashboard/$teamSlug/$projectId': typeof DashboardTeamSlugProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/mono': typeof MonoRoute
  '/sign-in': typeof SignInRouteWithChildren
  '/sign-up': typeof SignUpRouteWithChildren
  '/dashboard/$teamSlug': typeof DashboardTeamSlugRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/share/$token': typeof ShareTokenRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/$teamSlug/$projectId': typeof DashboardTeamSlugProjectIdRouteWithChildren
  '/dashboard/$teamSlug/settings': typeof DashboardTeamSlugSettingsRoute
  '/dashboard/$teamSlug/': typeof DashboardTeamSlugIndexRoute
  '/dashboard/$teamSlug/$projectId/$videoId': typeof DashboardTeamSlugProjectIdVideoIdRoute
  '/dashboard/$teamSlug/$projectId/': typeof DashboardTeamSlugProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/mono'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard/$teamSlug'
    | '/invite/$token'
    | '/share/$token'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/dashboard/'
    | '/dashboard/$teamSlug/$projectId'
    | '/dashboard/$teamSlug/settings'
    | '/dashboard/$teamSlug/'
    | '/dashboard/$teamSlug/$projectId/$videoId'
    | '/dashboard/$teamSlug/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mono'
    | '/sign-in'
    | '/sign-up'
    | '/invite/$token'
    | '/share/$token'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/dashboard'
    | '/dashboard/$teamSlug/settings'
    | '/dashboard/$teamSlug'
    | '/dashboard/$teamSlug/$projectId/$videoId'
    | '/dashboard/$teamSlug/$projectId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/mono'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard/$teamSlug'
    | '/invite/$token'
    | '/share/$token'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/dashboard/'
    | '/dashboard/$teamSlug/$projectId'
    | '/dashboard/$teamSlug/settings'
    | '/dashboard/$teamSlug/'
    | '/dashboard/$teamSlug/$projectId/$videoId'
    | '/dashboard/$teamSlug/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  MonoRoute: typeof MonoRoute
  SignInRoute: typeof SignInRouteWithChildren
  SignUpRoute: typeof SignUpRouteWithChildren
  InviteTokenRoute: typeof InviteTokenRoute
  ShareTokenRoute: typeof ShareTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mono': {
      id: '/mono'
      path: '/mono'
      fullPath: '/mono'
      preLoaderRoute: typeof MonoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof SignUpRoute
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof SignInRoute
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$teamSlug': {
      id: '/dashboard/$teamSlug'
      path: '/$teamSlug'
      fullPath: '/dashboard/$teamSlug'
      preLoaderRoute: typeof DashboardTeamSlugRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/$teamSlug/': {
      id: '/dashboard/$teamSlug/'
      path: '/'
      fullPath: '/dashboard/$teamSlug/'
      preLoaderRoute: typeof DashboardTeamSlugIndexRouteImport
      parentRoute: typeof DashboardTeamSlugRoute
    }
    '/dashboard/$teamSlug/settings': {
      id: '/dashboard/$teamSlug/settings'
      path: '/settings'
      fullPath: '/dashboard/$teamSlug/settings'
      preLoaderRoute: typeof DashboardTeamSlugSettingsRouteImport
      parentRoute: typeof DashboardTeamSlugRoute
    }
    '/dashboard/$teamSlug/$projectId': {
      id: '/dashboard/$teamSlug/$projectId'
      path: '/$projectId'
      fullPath: '/dashboard/$teamSlug/$projectId'
      preLoaderRoute: typeof DashboardTeamSlugProjectIdRouteImport
      parentRoute: typeof DashboardTeamSlugRoute
    }
    '/dashboard/$teamSlug/$projectId/': {
      id: '/dashboard/$teamSlug/$projectId/'
      path: '/'
      fullPath: '/dashboard/$teamSlug/$projectId/'
      preLoaderRoute: typeof DashboardTeamSlugProjectIdIndexRouteImport
      parentRoute: typeof DashboardTeamSlugProjectIdRoute
    }
    '/dashboard/$teamSlug/$projectId/$videoId': {
      id: '/dashboard/$teamSlug/$projectId/$videoId'
      path: '/$videoId'
      fullPath: '/dashboard/$teamSlug/$projectId/$videoId'
      preLoaderRoute: typeof DashboardTeamSlugProjectIdVideoIdRouteImport
      parentRoute: typeof DashboardTeamSlugProjectIdRoute
    }
  }
}

interface DashboardTeamSlugProjectIdRouteChildren {
  DashboardTeamSlugProjectIdVideoIdRoute: typeof DashboardTeamSlugProjectIdVideoIdRoute
  DashboardTeamSlugProjectIdIndexRoute: typeof DashboardTeamSlugProjectIdIndexRoute
}

const DashboardTeamSlugProjectIdRouteChildren: DashboardTeamSlugProjectIdRouteChildren =
  {
    DashboardTeamSlugProjectIdVideoIdRoute:
      DashboardTeamSlugProjectIdVideoIdRoute,
    DashboardTeamSlugProjectIdIndexRoute: DashboardTeamSlugProjectIdIndexRoute,
  }

const DashboardTeamSlugProjectIdRouteWithChildren =
  DashboardTeamSlugProjectIdRoute._addFileChildren(
    DashboardTeamSlugProjectIdRouteChildren,
  )

interface DashboardTeamSlugRouteChildren {
  DashboardTeamSlugProjectIdRoute: typeof DashboardTeamSlugProjectIdRouteWithChildren
  DashboardTeamSlugSettingsRoute: typeof DashboardTeamSlugSettingsRoute
  DashboardTeamSlugIndexRoute: typeof DashboardTeamSlugIndexRoute
}

const DashboardTeamSlugRouteChildren: DashboardTeamSlugRouteChildren = {
  DashboardTeamSlugProjectIdRoute: DashboardTeamSlugProjectIdRouteWithChildren,
  DashboardTeamSlugSettingsRoute: DashboardTeamSlugSettingsRoute,
  DashboardTeamSlugIndexRoute: DashboardTeamSlugIndexRoute,
}

const DashboardTeamSlugRouteWithChildren =
  DashboardTeamSlugRoute._addFileChildren(DashboardTeamSlugRouteChildren)

interface DashboardRouteRouteChildren {
  DashboardTeamSlugRoute: typeof DashboardTeamSlugRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardTeamSlugRoute: DashboardTeamSlugRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface SignInRouteChildren {
  SignInSplatRoute: typeof SignInSplatRoute
}

const SignInRouteChildren: SignInRouteChildren = {
  SignInSplatRoute: SignInSplatRoute,
}

const SignInRouteWithChildren =
  SignInRoute._addFileChildren(SignInRouteChildren)

interface SignUpRouteChildren {
  SignUpSplatRoute: typeof SignUpSplatRoute
}

const SignUpRouteChildren: SignUpRouteChildren = {
  SignUpSplatRoute: SignUpSplatRoute,
}

const SignUpRouteWithChildren =
  SignUpRoute._addFileChildren(SignUpRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  MonoRoute: MonoRoute,
  SignInRoute: SignInRouteWithChildren,
  SignUpRoute: SignUpRouteWithChildren,
  InviteTokenRoute: InviteTokenRoute,
  ShareTokenRoute: ShareTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
